<?php 
//aqui se obtendra la base de datos el numero empleados
//$nombre=$_POST['empresa'];
//sera asigando a la variable
$numero_empleados= $_POST['sucursal'];

?>
<!DOCTYPE html>                                                                                                                                                                                                                                                                                                                                                                 
<html>                                                                                                                                                                                                                                                                                                                                                                  
<head>                                                                                                                                                                                                                                                                                                                                                                  

    <meta charset="utf-8">                                                                                                                                                                                                                                                                                                                                                                  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">                                                                                                                                                                                                                                                                                                                                                                  

    <title>Cuestionario</title>                                                                                                                                                                                                                                                                                                                                                                 

    <link href="css/bootstrap.min.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="css/plugins/iCheck/custom.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="css/plugins/steps/jquery.steps.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                   
    <link href="css/animate.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                  
    <link href="css/style.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <script src="https://kit.fontawesome.com/473290e8a6.js"></script>  
    
    <style>
        .blanco{
            background-color: inherit;
            border: 2px solid #e7eaec;
            display: block; padding: 10px 15px;
             position: relative  
        }
        .gris{
            background-color: #e7eaec;
            border: 2px solid #e7eaec;
            display: block; padding: 10px 15px; 
            position: relative
        }
        #content1{
            display: none;
        }
        #content2{
            display: none;
        }
        .reloj{
        color: white;
        background-color: #1AB394;
        padding: 5px;
        font-size: 14px;
        font-family: monospace;
    }
    </style>
   
</head>                                                                                                                                                                                                                                                                                                                                                                 

<body>                                                                                                                                                                                                                                                                                                                                                                  
<div id="wrapper">                                                                                                                                                                                                                                                                                                                                                                  
<?php include 'MenuConsultor.html'; ?>                                                                                                                                                                                                                                                                                                                                                                     
<div id="page-wrapper" class="gray-bg">                                                                                                                                                                                                                                                                                                                                                                     
<?php include 'Nav.html'; ?>                                                                                                                                                                                                                                                                                                                                                                    
<div class="wrapper wrapper-content">                                                                                                                                                                                                                                                                                                                                                                   
<div class="row">                                                                                                                                                                                                                                                                                                                                                                   
                <div class="col-lg-12">                                                                                                                                                                                                                                                                                                                                                                 
                    <div class="ibox">                                                                                                                                                                                                                                                                                                                                                                  
                        <div class="ibox-title"> 
                             <div class="row"> 
                             <div class="col-xs-12 col-md-10"><h2><b>Encuesta</b></h2></div>
                                <div class="col-xs-6 col-md-2"> 
                                <!-- <button onclick="startWorker()">Start</button> 
                                <button onclick="stopWorker()">Stop</button> -->

<div id="contenedor" style="display: inline-flex;">
        <div class="reloj" id="horas">00</div>
        <div class="reloj">:</div>
        <div class="reloj" id="minutos">00</div>
        <div class="reloj">:</div>
        <div class="reloj" id="segundos">00</div>
        <!-- <div class="reloj">:</div>
        <div class="reloj" id="centesimas">00</div> -->

    </div>
                                </div>                                                                                                                                                                                                                                                                                                                                                                  
                           
                              </div>                                                                                                                                                                                                                                                                                                                                                               
                            <div class="ibox-tools">                                                                                                                                                                                                                                                                                                                                                                    
                            
                             
                            </div>                                                                                                                                                                                                                                                                                                                                                                
                        </div>                                                                                                                                                                                                                                                                                                                                                                  
                        <div class="ibox-content">                                                                                                                                                                                                                                                                                                                                                                  

                            <form id="form" method="POST" action="RegistrarEncuesta.php" class="wizard-big">                                                                                                                                                                                                                                                                                                                                                                  
                                <h1>Datos del Trabajador</h1>                                                                                                                                                                                                                                                                                                                                                                   
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                <?php include 'DatosEmpleado.php'; ?>
                                </fieldset> 
                                <h1>ET</h1>                                                                                                                                                                                                                                                                                                                                                                 
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                   
            <!-- final row -->   <?php include 'ET.php'; ?>
                                </fieldset>                                                                                                                                                                                                                                                                                                                                                                 
                                <?php if ($numero_empleados<=50): ?>
                                <h1>GR II</h1>                                                                                                                                                                                                                                                                                                                                                                  
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                <?php include 'GRII.php'; ?>
                                </fieldset> 
                                <?php else: ?>                                                                                                                                                                                                                                                                                                                                                                
                                <h1>GR III</h1>                                                                                                                                                                                                                                                                                                                                                                 
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                <?php include 'GRIII.php'; ?>

                                </fieldset> 
                                <?php endif ?>                                                                                                                                                                                                                                                                                                                                                                
                                <h1>Finalizar</h1>                                                                                                                                                                                                                                                                                                                                                                  
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                    <h2>Terms and Conditions</h2>                                                                                                                                                                                                                                                                                                                                                                   
                                    <input id="acceptTerms" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms">Acepto haber contestado el cuestionario correctamente.</label>                                                                                                                                                                                                                                                                                                                                                                    
                                </fieldset>                                                                                                                                                                                                                                                                                                                                                                 
                            </form>                                                                                                                                                                                                                                                                                                                                                                 
                        </div>                                                                                                                                                                                                                                                                                                                                                                  
                    </div>                                                                                                                                                                                                                                                                                                                                                                  
                    </div>                                                                                                                                                                                                                                                                                                                                                                  

                </div>                                                                                                                                                                                                                                                                                                                                                                  
  <?php include 'footer.html'; ?>                                                                                                                                                                                                                                                                                                                                                                       
</div>                                                                                                                                                                                                                                                                                                                                                                  

</div>                                                                                                                                                                                                                                                                                                                                                                  
</div>                                                                                                                                                                                                                                                                                                                                                                  


   <!-- Mainly scripts -->                                                                                                                                                                                                                                                                                                                                                                  
   <script src="js/jquery-3.1.1.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                   
    <script src="js/bootstrap.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                 
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>                                                                                                                                                                                                                                                                                                                                                                    
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                  

    <!-- Custom and plugin javascript -->                                                                                                                                                                                                                                                                                                                                                                   
    <script src="js/inspinia.js"></script>                                                                                                                                                                                                                                                                                                                                                                  
    <script src="js/plugins/pace/pace.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                 

    <!-- Steps -->                                                                                                                                                                                                                                                                                                                                                                  
    <script src="js/plugins/steps/jquery.steps.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                    

    <!-- Jquery Validate -->                                                                                                                                                                                                                                                                                                                                                                    
    <script src="js/plugins/validate/jquery.validate.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                  
    <script src="js/demo_workers.js"></script> 

    <script>                                                                                                                                                                                                                                                                                                                                                                    
        $(document).ready(function(){                                                                                                                                                                                                                                                                                                                                                                   
            $("#wizard").steps();                                                                                                                                                                                                                                                                                                                                                                   
            $("#form").steps({                                                                                                                                                                                                                                                                                                                                                                  
                bodyTag: "fieldset",                                                                                                                                                                                                                                                                                                                                                                    
                onStepChanging: function (event, currentIndex, newIndex)                                                                                                                                                                                                                                                                                                                                                                    
                {                                                                                                                                                                                                                                                                                                                                                                   
                    // Always allow going backward even if the current step contains invalid fields!                                                                                                                                                                                                                                                                                                                                                                    
                    if (currentIndex > newIndex)                                                                                                                                                                                                                                                                                                                                                                    
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        return true;                                                                                                                                                                                                                                                                                                                                                                    
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    // Forbid suppressing "Warning" step if the user is to young                                                                                                                                                                                                                                                                                                                                                                    
                    if (newIndex === 3 && Number($("#age").val()) < 18)                                                                                                                                                                                                                                                                                                                                                                 
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        return false;                                                                                                                                                                                                                                                                                                                                                                   
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    var form = $(this);                                                                                                                                                                                                                                                                                                                                                                 

                    // Clean up if user went backward before                                                                                                                                                                                                                                                                                                                                                                    
                    if (currentIndex < newIndex)                                                                                                                                                                                                                                                                                                                                                                    
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        // To remove error styles                                                                                                                                                                                                                                                                                                                                                                   
                        $(".body:eq(" + newIndex + ") label.error", form).remove();                                                                                                                                                                                                                                                                                                                                                                 
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");                                                                                                                                                                                                                                                                                                                                                                  
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    // Disable validation on fields that are disabled or hidden.                                                                                                                                                                                                                                                                                                                                                                    
                    form.validate().settings.ignore = ":disabled,:hidden";                                                                                                                                                                                                                                                                                                                                                                  

                    // Start validation; Prevent going forward if false                                                                                                                                                                                                                                                                                                                                                                 
                    return form.valid();                                                                                                                                                                                                                                                                                                                                                                    
                },                                                                                                                                                                                                                                                                                                                                                                  
                onStepChanged: function (event, currentIndex, priorIndex)                                                                                                                                                                                                                                                                                                                                                                   
                {                                                                                                                                                                                                                                                                                                                                                                   
                    // Suppress (skip) "Warning" step if the user is old enough.                                                                                                                                                                                                                                                                                                                                                                    
                    if (currentIndex === 2 && Number($("#age").val()) >= 18)                                                                                                                                                                                                                                                                                                                                                                    
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        $(this).steps("next");                                                                                                                                                                                                                                                                                                                                                                  
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.                                                                                                                                                                                                                                                                                                                                                                 
                    if (currentIndex === 2 && priorIndex === 3 && priorIndex === 4)                                                                                                                                                                                                                                                                                                                                                                 
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        $(this).steps("previous");                                                                                                                                                                                                                                                                                                                                                                  
                    }                                                                                                                                                                                                                                                                                                                                                                   
                },                                                                                                                                                                                                                                                                                                                                                                  
                onFinishing: function (event, currentIndex)                                                                                                                                                                                                                                                                                                                                                                 
                {                                                                                                                                                                                                                                                                                                                                                                   
                    var form = $(this);                                                                                                                                                                                                                                                                                                                                                                 

                    // Disable validation on fields that are disabled.                                                                                                                                                                                                                                                                                                                                                                  
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)                                                                                                                                                                                                                                                                                                                                                                   
                    form.validate().settings.ignore = ":disabled";                                                                                                                                                                                                                                                                                                                                                                  

                    // Start validation; Prevent form submission if false                                                                                                                                                                                                                                                                                                                                                                   
                    return form.valid();                                                                                                                                                                                                                                                                                                                                                                    
                },                                                                                                                                                                                                                                                                                                                                                                  
                onFinished: function (event, currentIndex)                                                                                                                                                                                                                                                                                                                                                                  
                {                                                                                                                                                                                                                                                                                                                                                                   
                    var form = $(this);                                                                                                                                                                                                                                                                                                                                                                 

                    // Submit form input                                                                                                                                                                                                                                                                                                                                                                    
                    form.submit();                                                                                                                                                                                                                                                                                                                                                                  
                }                                                                                                                                                                                                                                                                                                                                                                   
            }).validate({                                                                                                                                                                                                                                                                                                                                                                   
                        errorPlacement: function (error, element)                                                                                                                                                                                                                                                                                                                                                                   
                        {                                                                                                                                                                                                                                                                                                                                                                   
                            element.before(error);                                                                                                                                                                                                                                                                                                                                                                  
                        },                                                                                                                                                                                                                                                                                                                                                                  
                        rules: {                                                                                                                                                                                                                                                                                                                                                                    
                            confirm: {                                                                                                                                                                                                                                                                                                                                                                  
                                equalTo: "#password"                                                                                                                                                                                                                                                                                                                                                                    
                            }                                                                                                                                                                                                                                                                                                                                                                   
                        }                                                                                                                                                                                                                                                                                                                                                                   
                    });                                                                                                                                                                                                                                                                                                                                                                 
       });                                                                                                                                                                                                                                                                                                                                                                  
    </script>                                                                                                                                                                                                                                                                                                                                                                   
 <!-- iCheck -->                                                                                                                                                                                                                                                                                                                                                                    
 <script src="js/plugins/iCheck/icheck.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                    
        <script>                                                                                                                                                                                                                                                                                                                                                                    
            $(document).ready(function () { 
                 
                $('.i-checks').iCheck({                                                                                                                                                                                                                                                                                                                                                                 
                    checkboxClass: 'icheckbox_square-green',                                                                                                                                                                                                                                                                                                                                                                    
                    radioClass: 'iradio_square-green',  
                                                                                                                                                                                                                                                                                                                                                      
                }); 
                 
                                                                                                                                                                                                                                                                                                                                                             
            });                                                                                                                                                                                                                                                                                                                                                                 
        </script>                                                                                                                                                                                                                                                                                                                                                                   
<script>
   var w;

    $(document).ready(function() {
        if (typeof(Worker) !== "undefined") {
    if (typeof(w) == "undefined") {
      w = new Worker("js/demo_workers.js");
    }
    w.onmessage = function(event) {

      document.getElementById("horas").innerHTML = event.data.horas;
       document.getElementById("minutos").innerHTML = event.data.minutos;
        document.getElementById("segundos").innerHTML = event.data.segundos;
        //  document.getElementById("centesimas").innerHTML = event.data.centesimas;
    };
  } else {
    document.getElementById("result").innerHTML = "Sorry! No Web Worker support.";
  }
  function stopWorker() {  
  w.terminate();
  w = undefined;
}
});
</script>

</body>                                                                                                                                                                                                                                                                                                                                                                 


</html>                                                                                                                                                                                                                                                                                                                                                                 
