<?php 
//aqui se obtendra la base de datos el numero empleados
//sera asigando a la variable
$numero_empleados=50;
?>
<!DOCTYPE html>                                                                                                                                                                                                                                                                                                                                                                 
<html>                                                                                                                                                                                                                                                                                                                                                                  
<head>                                                                                                                                                                                                                                                                                                                                                                  

    <meta charset="utf-8">                                                                                                                                                                                                                                                                                                                                                                  
    <meta name="viewport" content="width=device-width, initial-scale=1.0">                                                                                                                                                                                                                                                                                                                                                                  

    <title>Cuestionario</title>                                                                                                                                                                                                                                                                                                                                                                 

    <link href="css/bootstrap.min.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="css/plugins/iCheck/custom.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="css/plugins/steps/jquery.steps.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                   
    <link href="css/animate.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                  
    <link href="css/style.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <link href="css/plugins/awesome-bootstrap-checkbox/awesome-bootstrap-checkbox.css" rel="stylesheet">                                                                                                                                                                                                                                                                                                                                                                    
    <script src="https://kit.fontawesome.com/473290e8a6.js"></script>  
    
    <style>
        .blanco{
            background-color: inherit;
            border: 2px solid #e7eaec;
            display: block; padding: 10px 15px;
             position: relative  
        }
        .gris{
            background-color: #e7eaec;
            border: 2px solid #e7eaec;
            display: block; padding: 10px 15px; 
            position: relative
        }
      
    </style>
   
</head>                                                                                                                                                                                                                                                                                                                                                                 

<body>                                                                                                                                                                                                                                                                                                                                                                  
<div id="wrapper">                                                                                                                                                                                                                                                                                                                                                                  
<?php include 'Slide-Menu.html'; ?>                                                                                                                                                                                                                                                                                                                                                                     
<div id="page-wrapper" class="gray-bg">                                                                                                                                                                                                                                                                                                                                                                     
<?php include 'Nav.html'; ?>                                                                                                                                                                                                                                                                                                                                                                    
<div class="wrapper wrapper-content">                                                                                                                                                                                                                                                                                                                                                                   
<div class="row">                                                                                                                                                                                                                                                                                                                                                                   
                <div class="col-lg-12">                                                                                                                                                                                                                                                                                                                                                                 
                    <div class="ibox">                                                                                                                                                                                                                                                                                                                                                                  
                        <div class="ibox-title"> 
                             <div class="row"> 
                             <div class="col-xs-12 col-md-3"><h2><b>Encuesta</b></h2></div>
                                <div class="col-xs-6 col-md-6"> <h2 class="text-navy"><b>(Nombre de la Empresa)</b></h2></div>                                                                                                                                                                                                                                                                                                                                                                  
                           
                              </div>                                                                                                                                                                                                                                                                                                                                                               
                            <div class="ibox-tools">                                                                                                                                                                                                                                                                                                                                                                    
                            
                             
                            </div>                                                                                                                                                                                                                                                                                                                                                                
                        </div>                                                                                                                                                                                                                                                                                                                                                                  
                        <div class="ibox-content">                                                                                                                                                                                                                                                                                                                                                                  

                            <form id="form" action="#" class="wizard-big">                                                                                                                                                                                                                                                                                                                                                                  
                                <h1>Datos del Trabajador</h1>                                                                                                                                                                                                                                                                                                                                                                   
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                <?php include 'Cuestionario1.php'; ?>
                                </fieldset> <!--  fasdfdsaf                                                                                                                                                                                                                                                                                                                                                                -->
                                <h1>ET</h1>                                                                                                                                                                                                                                                                                                                                                                 
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                   
            <!-- final row -->   <?php include 'Cuestionario2.php'; ?>
                                </fieldset>                                                                                                                                                                                                                                                                                                                                                                 
                                <?php if ($numero_empleados<=50): ?>
                                <h1>GR II</h1>                                                                                                                                                                                                                                                                                                                                                                  
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                <?php include 'Cuestionario3.php'; ?>
                                </fieldset> 
                                <?php else: ?>                                                                                                                                                                                                                                                                                                                                                                
                                <h1>GR III</h1>                                                                                                                                                                                                                                                                                                                                                                 
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                <?php include 'Cuestionario4.php'; ?>

                                </fieldset> 
                                <?php endif ?>                                                                                                                                                                                                                                                                                                                                                                
                                <h1>Finalizar</h1>                                                                                                                                                                                                                                                                                                                                                                  
                                <fieldset>                                                                                                                                                                                                                                                                                                                                                                  
                                    <h2>Terms and Conditions</h2>                                                                                                                                                                                                                                                                                                                                                                   
                                    <input id="acceptTerms" name="acceptTerms" type="checkbox" class="required"> <label for="acceptTerms">I agree with the Terms and Conditions.</label>                                                                                                                                                                                                                                                                                                                                                                    
                                </fieldset>                                                                                                                                                                                                                                                                                                                                                                 
                            </form>                                                                                                                                                                                                                                                                                                                                                                 
                        </div>                                                                                                                                                                                                                                                                                                                                                                  
                    </div>                                                                                                                                                                                                                                                                                                                                                                  
                    </div>                                                                                                                                                                                                                                                                                                                                                                  

                </div>                                                                                                                                                                                                                                                                                                                                                                  
  <?php include 'footer.html'; ?>                                                                                                                                                                                                                                                                                                                                                                       
</div>                                                                                                                                                                                                                                                                                                                                                                  

</div>                                                                                                                                                                                                                                                                                                                                                                  
</div>                                                                                                                                                                                                                                                                                                                                                                  


   <!-- Mainly scripts -->                                                                                                                                                                                                                                                                                                                                                                  
   <script src="js/jquery-3.1.1.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                   
    <script src="js/bootstrap.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                 
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>                                                                                                                                                                                                                                                                                                                                                                    
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                  

    <!-- Custom and plugin javascript -->                                                                                                                                                                                                                                                                                                                                                                   
    <script src="js/inspinia.js"></script>                                                                                                                                                                                                                                                                                                                                                                  
    <script src="js/plugins/pace/pace.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                 

    <!-- Steps -->                                                                                                                                                                                                                                                                                                                                                                  
    <script src="js/plugins/steps/jquery.steps.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                    

    <!-- Jquery Validate -->                                                                                                                                                                                                                                                                                                                                                                    
    <script src="js/plugins/validate/jquery.validate.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                  
    

    <script>                                                                                                                                                                                                                                                                                                                                                                    
        $(document).ready(function(){                                                                                                                                                                                                                                                                                                                                                                   
            $("#wizard").steps();                                                                                                                                                                                                                                                                                                                                                                   
            $("#form").steps({                                                                                                                                                                                                                                                                                                                                                                  
                bodyTag: "fieldset",                                                                                                                                                                                                                                                                                                                                                                    
                onStepChanging: function (event, currentIndex, newIndex)                                                                                                                                                                                                                                                                                                                                                                    
                {                                                                                                                                                                                                                                                                                                                                                                   
                    // Always allow going backward even if the current step contains invalid fields!                                                                                                                                                                                                                                                                                                                                                                    
                    if (currentIndex > newIndex)                                                                                                                                                                                                                                                                                                                                                                    
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        return true;                                                                                                                                                                                                                                                                                                                                                                    
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    // Forbid suppressing "Warning" step if the user is to young                                                                                                                                                                                                                                                                                                                                                                    
                    if (newIndex === 3 && Number($("#age").val()) < 18)                                                                                                                                                                                                                                                                                                                                                                 
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        return false;                                                                                                                                                                                                                                                                                                                                                                   
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    var form = $(this);                                                                                                                                                                                                                                                                                                                                                                 

                    // Clean up if user went backward before                                                                                                                                                                                                                                                                                                                                                                    
                    if (currentIndex < newIndex)                                                                                                                                                                                                                                                                                                                                                                    
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        // To remove error styles                                                                                                                                                                                                                                                                                                                                                                   
                        $(".body:eq(" + newIndex + ") label.error", form).remove();                                                                                                                                                                                                                                                                                                                                                                 
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");                                                                                                                                                                                                                                                                                                                                                                  
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    // Disable validation on fields that are disabled or hidden.                                                                                                                                                                                                                                                                                                                                                                    
                    form.validate().settings.ignore = ":disabled,:hidden";                                                                                                                                                                                                                                                                                                                                                                  

                    // Start validation; Prevent going forward if false                                                                                                                                                                                                                                                                                                                                                                 
                    return form.valid();                                                                                                                                                                                                                                                                                                                                                                    
                },                                                                                                                                                                                                                                                                                                                                                                  
                onStepChanged: function (event, currentIndex, priorIndex)                                                                                                                                                                                                                                                                                                                                                                   
                {                                                                                                                                                                                                                                                                                                                                                                   
                    // Suppress (skip) "Warning" step if the user is old enough.                                                                                                                                                                                                                                                                                                                                                                    
                    if (currentIndex === 2 && Number($("#age").val()) >= 18)                                                                                                                                                                                                                                                                                                                                                                    
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        $(this).steps("next");                                                                                                                                                                                                                                                                                                                                                                  
                    }                                                                                                                                                                                                                                                                                                                                                                   

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.                                                                                                                                                                                                                                                                                                                                                                 
                    if (currentIndex === 2 && priorIndex === 3)                                                                                                                                                                                                                                                                                                                                                                 
                    {                                                                                                                                                                                                                                                                                                                                                                   
                        $(this).steps("previous");                                                                                                                                                                                                                                                                                                                                                                  
                    }                                                                                                                                                                                                                                                                                                                                                                   
                },                                                                                                                                                                                                                                                                                                                                                                  
                onFinishing: function (event, currentIndex)                                                                                                                                                                                                                                                                                                                                                                 
                {                                                                                                                                                                                                                                                                                                                                                                   
                    var form = $(this);                                                                                                                                                                                                                                                                                                                                                                 

                    // Disable validation on fields that are disabled.                                                                                                                                                                                                                                                                                                                                                                  
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)                                                                                                                                                                                                                                                                                                                                                                   
                    form.validate().settings.ignore = ":disabled";                                                                                                                                                                                                                                                                                                                                                                  

                    // Start validation; Prevent form submission if false                                                                                                                                                                                                                                                                                                                                                                   
                    return form.valid();                                                                                                                                                                                                                                                                                                                                                                    
                },                                                                                                                                                                                                                                                                                                                                                                  
                onFinished: function (event, currentIndex)                                                                                                                                                                                                                                                                                                                                                                  
                {                                                                                                                                                                                                                                                                                                                                                                   
                    var form = $(this);                                                                                                                                                                                                                                                                                                                                                                 

                    // Submit form input                                                                                                                                                                                                                                                                                                                                                                    
                    form.submit();                                                                                                                                                                                                                                                                                                                                                                  
                }                                                                                                                                                                                                                                                                                                                                                                   
            }).validate({                                                                                                                                                                                                                                                                                                                                                                   
                        errorPlacement: function (error, element)                                                                                                                                                                                                                                                                                                                                                                   
                        {                                                                                                                                                                                                                                                                                                                                                                   
                            element.before(error);                                                                                                                                                                                                                                                                                                                                                                  
                        },                                                                                                                                                                                                                                                                                                                                                                  
                        rules: {                                                                                                                                                                                                                                                                                                                                                                    
                            confirm: {                                                                                                                                                                                                                                                                                                                                                                  
                                equalTo: "#password"                                                                                                                                                                                                                                                                                                                                                                    
                            }                                                                                                                                                                                                                                                                                                                                                                   
                        }                                                                                                                                                                                                                                                                                                                                                                   
                    });                                                                                                                                                                                                                                                                                                                                                                 
       });                                                                                                                                                                                                                                                                                                                                                                  
    </script>                                                                                                                                                                                                                                                                                                                                                                   
 <!-- iCheck -->                                                                                                                                                                                                                                                                                                                                                                    
 <script src="js/plugins/iCheck/icheck.min.js"></script>                                                                                                                                                                                                                                                                                                                                                                    
        <script>                                                                                                                                                                                                                                                                                                                                                                    
            $(document).ready(function () { 
                 
                $('.i-checks').iCheck({                                                                                                                                                                                                                                                                                                                                                                 
                    checkboxClass: 'icheckbox_square-green',                                                                                                                                                                                                                                                                                                                                                                    
                    radioClass: 'iradio_square-green',  
                                                                                                                                                                                                                                                                                                                                                      
                }); 
                 
                                                                                                                                                                                                                                                                                                                                                             
            });                                                                                                                                                                                                                                                                                                                                                                 
        </script>                                                                                                                                                                                                                                                                                                                                                                   
<script>
    $(document).ready(function() {
    $("check").click(function(event){
        var valor = $(event.target).val();
        if(valor =="si"){
            $("#content").show();
            // $("#div2").hide();
        } 
        // else if (valor == "Ventanilla") {
        //     $("#div1").hide();
        //     $("#div2").show();
        // } else { 
        //     // Otra cosa
        // }
    });
});
</script>

</body>                                                                                                                                                                                                                                                                                                                                                                 


</html>                                                                                                                                                                                                                                                                                                                                                                 
